# Generated by Django 4.2.18 on 2025-02-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_remove_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_confirmed_by_admin",
        ),
    ]
