# Generated by Django 4.2.18 on 2025-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0003_remove_customuser_is_confirmed_by_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
