# Generated by Django 5.1.7 on 2025-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_id", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("surname", models.CharField(blank=True, max_length=50, null=True)),
                ("phone_num", models.CharField(blank=True, max_length=50, null=True)),
                ("school", models.CharField(blank=True, max_length=50, null=True)),
                ("attempt", models.PositiveIntegerField()),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("base64", models.TextField()),
                ("array_data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_id", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("surname", models.CharField(blank=True, max_length=50, null=True)),
                ("phone_num", models.CharField(blank=True, max_length=50, null=True)),
                ("school", models.CharField(blank=True, max_length=50, null=True)),
                ("base64", models.TextField()),
                ("array_data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_id", models.IntegerField()),
                ("base64", models.TextField()),
                ("array_data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error", models.CharField(max_length=256)),
            ],
        ),
    ]
