# Generated by Django 4.2.18 on 2025-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumpyArrayModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.TextField()),
                ("base64", models.TextField()),
                ("array_data", models.BinaryField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
