# Generated by Django 5.1.7 on 2025-04-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examresult",
            name="passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="BestResult",
        ),
    ]
