# Generated by Django 4.2.18 on 2025-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='english',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='math',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
